---
title: "Academic Experience"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly
---

This is a page giving my academic and professional experience.

### Studies on the Prediction of Biological Activity of RDRP Inhibitors Based on Deep Learning

* Based on Graph Neural Networks (GNN) in deep learning methods, constructed a small molecule inhibitory activity classification model against RDRP, and increased the training and testing accuracy to more than 90%

* Used TANKBind model based on P2Rank to predict the binding pockets in RDRP with more than 18,000 in the laboratory molecular library, and found more than 3 novel pockets each in HCV 1b RDRP, DENV 2 RDRP and SARS-CoV-2 RDRP

* Screened out 722 molecules with novel binding sites and high inhibitory activity to all three RDRP, clustered these molecules with Morgan Fingerprints and found some molecular skeletons such as 2,1-Benzothiazine 2,2-Dioxides and 4-Biphenylacetic acid


### Studies on the Human-Animal Conflicts, Interfering Factors, and Risk Evaluation

* Primarily analyzed the four possible factors influencing the human-animal conflicts including economics, education, human activities, and geographical environment in six districts of Beijing, and selected ten sub evaluation index

* Adopted the Analytic Hierarchy Process and Principal Component Analysis to determine the factor weight to reduce the deficiency of high subjectivity when confirming the indicator direction

* Built linear regression model, and based on the comprehensive evaluation model to evaluate the human-animal conflicts risks, thus
giving some referential results for the sustainable development of human society















